# Generated by Django 3.1.1 on 2020-09-28 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=100000)),
                ('image', models.ImageField(null=True, upload_to='images/%Y/%b/%a/%d/%H/%M')),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=40, unique=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('added_date',),
            },
        ),
        migrations.CreateModel(
            name='YaridAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('lastname', models.CharField(max_length=20, unique=True)),
                ('Uemail', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('residence', models.CharField(max_length=30)),
                ('country_of_origin', models.CharField(max_length=30)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('reg_date',),
            },
        ),
        migrations.CreateModel(
            name='YaridMemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('respondent', 'respondent'), ('staff', 'Staff'), ('adminstaff', 'AdminStaff'), ('parent', 'Parent')], default='student', max_length=30, unique=True)),
                ('role_name_added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('role_name',),
            },
        ),
        migrations.CreateModel(
            name='StaffMemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffMemberprofiling_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('StaffMemberCourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members_course_name', to='API.surveytopics')),
                ('StaffMemberId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_Member_name', to='API.yaridaccount')),
                ('StaffMemberRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members_role_name', to='API.yaridmemberrole')),
            ],
            options={
                'ordering': ('StaffMemberprofiling_date',),
            },
        ),
        migrations.CreateModel(
            name='RespondentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Respondentprofiling_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('RespondentName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Member_name', to='API.yaridaccount')),
                ('RespondentRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_role_name', to='API.yaridmemberrole')),
            ],
            options={
                'ordering': ('Respondentprofiling_date',),
            },
        ),
        migrations.CreateModel(
            name='QuestionPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_body', models.TextField(max_length=100000)),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_image', models.ImageField(null=True, upload_to='images/%Y/%b/%a/%d/%H/%M')),
                ('poster_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posters_name', to='API.respondentprofile')),
            ],
            options={
                'ordering': ('posting_date',),
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagetitle', models.CharField(max_length=30)),
                ('messagebody', models.TextField(max_length=100000)),
                ('sendingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('recievername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever_name', to='API.respondentprofile')),
                ('sendername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_name', to='API.respondentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_marks', models.CharField(max_length=10)),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorder', to='API.staffmemberprofile')),
                ('respondent_marked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='API.respondentprofile')),
                ('survey_marked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_course', to='API.surveytopics')),
            ],
        ),
    ]
